### ISSUE TITLE
Update frontend 

### ISSUE THREAD

**Issue by gmax79** [johanbrandhorst/grpcweb-wasm-example#9]
Is it possible to adapt the frontend to the current standard versions of the grpc libraries without using the replace directive in go.mod ?

On Golang there is not enough grpc-web client, so as not to use the javascript version of the client for webasm applications.

**Comment by johanbrandhorst** [comment]
I don't have any intention to update this repo. It might be possible to replace grpcweb with https://connect.build in Go Wasm.
